src/main/java/lt/akademija/entities/Traukinys.java
package lt.akademija.entities;


import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.annotation.Generated;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

public class Traukinys implements Serializable {

	private static final long serialVersionUID = -192367291004010121L;
	
	@Id
	private Long numeris;
	private Date pagaminimoData;
	private String imone;
	private String miestas;
	
	@ManyToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	private List<Vagonas> vagonai;

	public Long getNumeris() {
		return numeris;
	}

	public void setNumberis(Long numberis) {
		this.numeris = numberis;
	}

	public Date getPagaminimoData() {
		return pagaminimoData;
	}

	public void setPagaminimoData(Date pagaminimoData) {
		this.pagaminimoData = pagaminimoData;
	}

	public String getImone() {
		return imone;
	}

	public void setImone(String imone) {
		this.imone = imone;
	}

	public String getMiestas() {
		return miestas;
	}

	public void setMiestas(String miestas) {
		this.miestas = miestas;
	}

	public List<Vagonas> getVagonai() {
		return vagonai;
	}

	public void setVagonai(List<Vagonas> vagonai) {
		this.vagonai = vagonai;
	}
	
	public void addVagonas(Vagonas a) {
		if (getVagonai() == null) {
			setVagonai(new ArrayList<>());
		} else {
			getVagonai().add(a);
		}
	}
}

src/main/java/lt/akademija/entities/Vagonas.java
package lt.akademija.entities;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.DiscriminatorColumn;
import javax.persistence.DiscriminatorType;
import javax.persistence.DiscriminatorValue;
import javax.persistence.Embedded;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Index;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;

public class Vagonas implements Serializable {

	private static final long serialVersionUID = 6417831368924888360L;

	@Id
	@GeneratedValue
	private Long id;
	
	@NotNull
	@NotBlank
	private BazinisVagonas bazinisVagonas;
	private String gamintojas;
	private int kiekis;
	private Long kaina;
	private int turis;
	
	private enum BazinisVagonas {
		KELEIVINIS, KROVININIS, LOKOMOTYVAS
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public BazinisVagonas getBazinisVagonas() {
		return bazinisVagonas;
	}

	public void setBazinisVagonas(BazinisVagonas bazinisVagonas) {
		this.bazinisVagonas = bazinisVagonas;
	}

	public String getGamintojas() {
		return gamintojas;
	}

	public void setGamintojas(String gamintojas) {
		this.gamintojas = gamintojas;
	}

	public int getKiekis() {
		return kiekis;
	}

	public void setKiekis(int kiekis) {
		this.kiekis = kiekis;
	}

	public Long getKaina() {
		return kaina;
	}

	public void setKaina(Long kaina) {
		this.kaina = kaina;
	}

	public int getTuris() {
		return turis;
	}

	public void setTuris(int turis) {
		this.turis = turis;
	}
		
	
}

src/main/java/lt/akademija/entities/VagonasKeleivinis.java
package lt.akademija.entities;

public class VagonasKeleivinis extends Vagonas{
	
	private KeleivinisKlase keleivinisKlase;
	
	private enum KeleivinisKlase {
		pirma, antra, trecia
	}

	public KeleivinisKlase getKeleivinisKlase() {
		return keleivinisKlase;
	}

	public void setKeleivinisKlase(KeleivinisKlase keleivinisKlase) {
		this.keleivinisKlase = keleivinisKlase;
	}
	
}

src/main/java/lt/akademija/entities/VagonasKrovininis.java
package lt.akademija.entities;

public class VagonasKrovininis extends Vagonas {

	private Long KrovininisGalia;

	public Long getKrovininisGalia() {
		return KrovininisGalia;
	}

	public void setKrovininisGalia(Long KrovininisGalia) {
		this.KrovininisGalia = KrovininisGalia;
	}
	
}

src/main/java/lt/akademija/entities/VagonasLokomotyvas.java
package lt.akademija.entities;

public class VagonasLokomotyvas extends Vagonas {

	private LokomotyvoTipas lokomotyvoTipas;
	
	private enum LokomotyvoTipas {
		traukiantis, stumiantis
	}

	public LokomotyvoTipas getLokomotyvoTipas() {
		return lokomotyvoTipas;
	}

	public void setLokomotyvoTipas(LokomotyvoTipas lokomotyvoTipas) {
		this.lokomotyvoTipas = lokomotyvoTipas;
	}
	
	
}

src/main/java/lt/akademija/entities/repositories/TraukinysRepository.java
package lt.akademija.entities.repositories;

import java.util.List;

import lt.akademija.entities.Traukinys;

public interface TraukinysRepository {

	public List<Traukinys> findAll();
	public void save(Traukinys traukinys);
	public void delete(Traukinys traukinys);
	
}

src/main/java/lt/akademija/entities/repositories/VagonasRepository.java
package lt.akademija.entities.repositories;

import java.util.List;

import lt.akademija.entities.Vagonas;

public interface VagonasRepository {
	
	public List<Vagonas> findAll();
	public void add(Vagonas naujasVagonas);
	public void delete(Vagonas vagonas);
	
}

src/main/java/lt/akademija/entities/repositories/jpa/TraukinysImpl.java
package lt.akademija.entities.repositories.jpa;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.akademija.entities.Traukinys;
import lt.akademija.entities.repositories.TraukinysRepository;


public class TraukinysImpl implements TraukinysRepository {
	static final Logger log = LoggerFactory.getLogger(TraukinysImpl.class);
	
	private EntityManagerFactory entityManagerFactory;

	public void setEntityManagerFactory(EntityManagerFactory emf) {
		this.entityManagerFactory = emf;
	}
	
	private EntityManager getEntityManager() {
		return entityManagerFactory.createEntityManager();
	}
	
	
	@Override
	public List<Traukinys> findAll() {
		
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Traukinys> cq = cb.createQuery(Traukinys.class);
			Root<Traukinys> root = cq.from(Traukinys.class);
			cq.select(root); // we select entity here
			TypedQuery<Traukinys> q = entityManager.createQuery(cq);
			return q.getResultList();
		} finally {
			entityManager.close();
		}
	}

	@Override
	public void save(Traukinys traukinys) {
		
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			entityManager.persist(traukinys);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
		
	}

	@Override
	public void delete(Traukinys traukinys) {
		
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			traukinys = entityManager.merge(traukinys);
			entityManager.remove(traukinys);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
		
	}

}

src/main/java/lt/akademija/entities/repositories/jpa/VagonasImpl.java
package lt.akademija.entities.repositories.jpa;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.NoResultException;
import javax.persistence.TypedQuery;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaQuery;
import javax.persistence.criteria.Root;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.akademija.entities.Traukinys;
import lt.akademija.entities.Vagonas;
import lt.akademija.entities.repositories.VagonasRepository;

public class VagonasImpl implements VagonasRepository {

	private EntityManagerFactory entityManagerFactory;

	public EntityManagerFactory getEntityManagerFactory() {
		return entityManagerFactory;
	}

	public void setEntityManagerFactory(EntityManagerFactory entityManagerFactory) {
		this.entityManagerFactory = entityManagerFactory;
	}
	
	@Override
	public List<Vagonas> findAll() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void add(Vagonas naujasVagonas) {
		EntityManager entityManager = getEntityManager();
		try {
			CriteriaBuilder cb = entityManager.getCriteriaBuilder();
			CriteriaQuery<Traukinys> cq = cb.createQuery(Traukinys.class);
			Root<Traukinys> root = cq.from(Traukinys.class);
			cq.select(root); // we select entity here
			TypedQuery<Traukinys> q = entityManager.createQuery(cq);
		} finally {
			entityManager.close();
		}
	}

	@Override
	public void delete(Vagonas vagonas) {
		
		EntityManager entityManager = getEntityManager();
		try {
			entityManager.getTransaction().begin();
			entityManager.remove(vagonas);
			entityManager.getTransaction().commit();
		} finally {
			entityManager.close();
		}
		
	}

	private EntityManager getEntityManager() {
		return entityManagerFactory.createEntityManager();
	}
}

src/main/java/lt/akademija/ui/controllers/AddNewVagonasPageBean.java
package lt.akademija.ui.controllers;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.akademija.entities.Traukinys;
import lt.akademija.entities.Vagonas;
import lt.akademija.entities.repositories.TraukinysRepository;
import lt.akademija.entities.repositories.VagonasRepository;



public class AddNewVagonasPageBean {

	private TraukinysRepository traukinysRepo;
	private VagonasRepository vagonasRepo;
	
	private TraukinysListPageBean traukinysListPageBean;
	
	private Vagonas newVagonas;
	
	public void init() {
		newVagonas = new Vagonas();
	}
	

	
	
}

src/main/java/lt/akademija/ui/controllers/TraukinysListPageBean.java
package lt.akademija.ui.controllers;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Date;
import java.util.List;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import javax.validation.Valid;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import lt.akademija.entities.Traukinys;
import lt.akademija.entities.Vagonas;
import lt.akademija.entities.repositories.TraukinysRepository;
import lt.akademija.entities.repositories.VagonasRepository;


public class TraukinysListPageBean {
	static final Logger log = LoggerFactory.getLogger(TraukinysListPageData.class);
	
	public static final String NAV_SHOW_ADD_VAGONAS = "show-add-vagonas";
	public static final String NAV_LIST_TRAUKINIAI = "list-traukiniai";
	
	public static class TraukinysListPageData implements Serializable {

		private static final long serialVersionUID = -7847613490719023414L;

		@Valid
		private Traukinys newTraukinys;

		@Valid
		private Traukinys currentTraukinys;
		
		private List<Traukinys> foundTraukinys;

		public void init() {
			newTraukinys = new Traukinys();
			foundTraukinys = new ArrayList<>();
		}


		public List<Traukinys> getFoundTraukinys() {
			return foundTraukinys;
		}

		public void setFoundTraukinys(List<Traukinys> foundTraukinys) {
			this.foundTraukinys = foundTraukinys;
		}

		public Traukinys getCurrentTraukinys() {
			return currentTraukinys;
		}

		public void setCurrentTraukinys(Traukinys currentTraukinys) {
			this.currentTraukinys = currentTraukinys;
		}

		public Traukinys getNewTraukinys() {
			return newTraukinys;
		}

		public void setNewTraukinys(Traukinys newTraukinys) {
			this.newTraukinys = newTraukinys;
		}
	} 



	private TraukinysRepository traukinysRepo;

	private TraukinysListPageData data;


	public String deleteSelected(Traukinys traukinys) {
		if (traukinys == null)
			FacesContext.getCurrentInstance().addMessage(null,
					new FacesMessage(FacesMessage.SEVERITY_WARN, "Warning!", "Traukinys yra null?"));
		else {
			traukinysRepo.delete(traukinys);
		}
		return NAV_LIST_TRAUKINIAI;
	}

	
	public String showAddVagonasPage(Traukinys a) {
		log.debug("Will store selected vagonas for later access in Add new Vagonas form: {}", a);
		data.currentTraukinys = a;
		return NAV_SHOW_ADD_VAGONAS;
	}

	public TraukinysListPageData getData() {
		return data;
	}

	public void setData(TraukinysListPageData data) {
		this.data = data;
	}

	public TraukinysRepository getTraukinysRepo() {
		return traukinysRepo;
	}

	public void setTraukinysRepo(TraukinysRepository traukinysRepo) {
		this.traukinysRepo = traukinysRepo;

	}

	public List<Traukinys> getTraukinysList() {
		return traukinysRepo.findAll();
	}
	
	
	
	
}

src/main/webapp/addVagonas.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>
			<p:messages id="messages" showDetail="true" autoUpdate="true"
				closable="true" />
			<p:panel id="basic" header="Traukinys" style="margin-bottom:20px">
				<h:panelGrid id="grid" columns="3" cellpadding="5">
					<h:outputLabel for="numeris" value="Traukinio numeris"></h:outputLabel>
					<h:inputText id="traukinio numeris" value="#{addVagonasPage.newVagonas.numeris}">
						<f:validateBean />
					</h:inputText>
					<p:message for="numeris" />
					<h:outputLabel for="pagaminimoData"
						value="Pagaminimo data (YYY-MM-DD)"></h:outputLabel>

					<h:inputText id="pagaminimoData"
						value="#{addVagonasPage.newVagonas.pagaminimoData}"
						converterMessage="Naudoti formatą YYYY-MM-DD">
						<f:convertDateTime pattern="yyyy-M-d" />
					</h:inputText>
					<p:message for="pagaminimoData" />
					
					<h:inputText id="imone"
						value="#{addVagonasPage.newVagonas.imone}"
						converterMessage="Naudoti formatą YYYY-MM-DD">
						<f:convertDateTime pattern="yyyy-M-d" />
					</h:inputText>
					<p:message for="pagaminimoData" />					
					
				</h:panelGrid>

				<h:commandButton action="#{addVagonasPage.addNew}" value="Pridėti naują"></h:commandButton>
			</p:panel>
		</h:form>

	</ui:define>

	<ui:define name="pavadinimas">
 	 	Pridėti naują traukinį
 	 </ui:define>

</ui:composition>

src/main/webapp/sablonas.xhtml
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets">
<h:head>
	<title>Traukinių sąstato valdymo programa - <ui:insert name="pavadinimas">
  		Pavadinimo nera
  	</ui:insert>
	</title>
	<!--   <h:outputStylesheet library="mano" name="failas.css"></h:outputStylesheet> -->
</h:head>
<h:body>
	<div id="container">
		<h:form>
			<p:tabMenu>
				<p:menuitem value="Traukiniai" outcome="list-traukiniai"
					icon="ui-icon-star">
				</p:menuitem>
			</p:tabMenu>
		</h:form>
		<div id="contents">
			<ui:insert name="turinys">
		  		Turinio nera
		  	</ui:insert>
		</div>
	</div>
</h:body>
</html>

src/main/webapp/traukiniai.xhtml
<ui:composition xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:p="http://primefaces.org/ui"
	xmlns:ui="http://java.sun.com/jsf/facelets" template="sablonas.xhtml">

	<ui:define name="turinys">
		<h:form>
			
			<p:messages id="messages" showDetail="false" autoUpdate="true"
				closable="true" />

			<p:dataTable value="#{traukinysListPage.traukinysList}" var="traukinys">
				<p:column headerText="numeris">
					<h:outputText value="#{traukinys.numeris}" />
				</p:column>

				<p:column headerText="Name">
					<h:outputText value="#{traukinys.name}" />
				</p:column>

				<p:column headerText="PagaminimoData">
					<h:outputText value="#{traukinys.pagaminimoData}" />
				</p:column>

				<p:column headerText="Vagonai">
					<h:dataTable value="#{traukinys.vagonai}" var="vagonas" border="0">
						<h:column>
		  						#{vagonas.bazinisVagonas} (#{vagonas.gamintojas})
	  					</h:column>
					</h:dataTable>
				</p:column>

				<p:column headerText="">
					<h:commandButton value="Trinti"
						action="#{traukinysListPage.deleteSelected(traukinys)}" />
					<h:commandButton value="Pridėti vagoną"
						action="#{traukinysListPage.showAddVagonasPage(traukinys)}" />
				</p:column>
			</p:dataTable>


		</h:form>


	</ui:define>

	<ui:define name="pavadinimas">
 	 	Pridėti naują vagoną
 	 </ui:define>

</ui:composition>